name: release

on:
  push:
    branches:
      - rust_basic_support_v2
    tags:
      - "*"
  pull_request: {}

jobs:
  ksc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: build-compiler
        run: |
          cd compiler
          export GIT_COMMIT=$(git log -1 --format=%h)
          export GIT_DATE_ISO=$(TZ=UTC git log -1 --date=iso-strict-local --format=%cd)
          export GIT_DATE=$(TZ=UTC git log -1 --date=format-local:%Y%m%d.%H%M%S --format=%cd)
          export KAITAI_STRUCT_VERSION=0.11-SNAPSHOT${GIT_DATE}.${GIT_COMMIT}

          echo "KAITAI_STRUCT_VERSION=$KAITAI_STRUCT_VERSION"

          cat /dev/null | sbt \
            compile \
            compilerJVM/stage \
            fastOptJS \
            buildNpmJsFile \
            buildNpmPackage \
            compilerJVM/debian:packageBin \
            compilerJVM/universal:packageBin

# TODO: add compilerJVM/rpm:packageBin

      - name: publish ksc to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kaitai-struct-compiler
          path: |
            compiler/js/target/scala-*/kaitai-struct-compiler-fastopt.js
            compiler/js/npm
            compiler/jvm/target/kaitai-struct-compiler_*_all.deb
            compiler/jvm/target/universal/kaitai-struct-compiler-*.zip

      - name: release ksc to artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "compiler/jvm/target/kaitai-struct-compiler_*_all.deb,compiler/jvm/target/universal/kaitai-struct-compiler-*.zip"
          body: "new release"